version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    build: ./backend-flask
    ports:
      - "4567:4567"

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
    build: ./frontend-react-js
    ports:
      - "3000:3000"

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  default:
    name: cruddur
